### ISSUE TITLE
Issue on 'vagrant up'

### ISSUE THREAD

**Issue by gragana** [andygabby/bionic64-k8s#1]
I haven't looked into this at all, just saw the red & figured I'd paste it before I lose it. :)
looks like it does it on all 4 nodes.

`
    k8s-node1: Setting up kubeadm (1.11.2-00) ...
    k8s-node1: Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
    k8s-node1: Executing: /lib/systemd/systemd-sysv-install enable docker
    k8s-node1: [preflight] running pre-flight checks
    k8s-node1: 	[WARNING RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs_sh ip_vs ip_vs_rr ip_vs_wrr] or no builtin kernel ipvs support: map[ip_vs:{} ip_vs_rr:{} ip_vs_wrr:{} ip_vs_sh:{} nf_conntrack_ipv4:{}]
    k8s-node1: you can solve this problem with following methods:
    k8s-node1:  1. Run 'modprobe -- ' to load missing kernel modules;
    k8s-node1: 2. Provide the missing builtin kernel ipvs support
    k8s-node1: I0910 16:36:25.534832    4562 kernel_validator.go:81] Validating kernel version
    k8s-node1: I0910 16:36:25.534905    4562 kernel_validator.go:96] Validating kernel config
    k8s-node1: 	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.12.1-ce. Max validated version: 17.03
    k8s-node1: [discovery] Trying to connect to API Server "10.4.2.10:6443"
`

**Comment by andygabby** [comment]
After the installation, a reboot is executed to make sure all updates (kernel and otherwise) are applied. As far as I can tell the modules are loaded properly by the time they are needed. Also if IPVS is not there I believe kubernetes will default to using iptables. Either way it all seems to work with my testing.
